# Generated by Django 2.2.1 on 2019-05-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('etc', models.CharField(max_length=250)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'unique_together': {('restaurant_id', 'user_id')},
            },
        ),
    ]
